const data = {
  teil1: [
    { word: "Arbeitsplatz für ihren Vater", number: 234 },
    { word: "Einkäufe im Internet", number: 13 },
    { word: "Computer", number: 24 },
    { word: "Einzelkind", number: 245 },
    { word: "Sport als für Kultur", number: 125 },
    { word: "Bus zur Arbeit", number: 23 },
    { word: "Arbeit zu fahren", number: 34 },
    { word: "In der Schule", number: 245 },
    { word: "Kinder", number: 245 },
    { word: "Urlaub", number: 125 },
    { word: "Fremdsprache", number: 245 },
    { word: "Handys", number: 14 },
  ],
  teil2: [
    { word: "UKI", number: 1 },
    { word: "Praktikum", number: 1 },
    { word: "tuernkerr", number: 1 },
  ],
  teil3: [
    { word: "Georg und Claudia", number: 25 },
    { word: "Meissner", number: 45 },
    { word: "Der Fahrer", number: 134 },
    { word: "Ingolstadt", number: 34 },
    { word: "Innenstadt", number: 13 },
    { word: "Prag", number: 35 },
    { word: "Hauptbahnhof", number: 245 },
    { word: "Griechenland", number: 235 },
    { word: "Norddeutschland", number: 23 },
    { word: "Füssen", number: 1 },
    { word: "Mannheim", number: 15 },
    { word: "Fahrer", number: 134 },
    { word: "Nebels", number: 245 },
  ],
};
